//! Guess MIME types based on the file extension.
//!
//! The actual code for the parser is generated by the build script (`build.rs`).
//!
//! This module re-exports the `MimeType` type.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/mime_data.rs"));
}

pub use generated::MimeType;

#[test]
fn guess_mime_types() {
    use std::ffi::OsString;

    assert_eq!(
        MimeType::from_extension(&OsString::from("png")),
        Some(MimeType::IMAGE)
    );

    assert_eq!(
        MimeType::from_extension(&OsString::from("webm")),
        Some(MimeType::VIDEO)
    );

    assert_eq!(MimeType::from_extension(&OsString::from("/")), None);
}
